INSERT INTO REGISTRO (email, seleccion)
VALUES
    ('usuario1@dominio.com', 'Pop'),
    ('usuario2@dominio.com', 'Rock'),
    ('usuario3@dominio.com', 'Electro'),
    ('usuario4@dominio.com', 'Jazz'),
    ('usuario5@dominio.com', 'Clasica'),
    ('usuario6@dominio.com', 'Clasica'),
    ('usuario7@dominio.com', 'Clasica'),
    ('usuario8@dominio.com', 'Rock'),
    ('usuario9@dominio.com', 'Rock'),
    ('usuario10@dominio.com', 'Rock'),
    ('usuario11@dominio.com', 'Rock'),
    ('usuario12@dominio.com', 'Rock'),
    ('usuario15@dominio.com', 'Pop'),
    ('usuario16@dominio.com', 'Pop'),
    ('usuario17@dominio.com', 'Jazz'),
    ('usuario18@dominio.com', 'Jazz'),
    ('usuario19@dominio.com', 'Electro'),
    ('usuario20@dominio.com', 'Pop');